TCC = tcc
TLIB = tlib
CFLAGS = -IC:\TC\INCLUDE -LC:\TC\LIB -ml

all: d13lib.lib

d13lib.lib: d13lib.obj
    $(TLIB) $@ +$^

d13lib.obj: d13lib.c
    $(TCC) -c $(CFLAGS) $<

clean:
    del d13lib.obj
    del d13lib.lib
