site_name: Draw13

theme:
  name: material
  features:
    - navigation.sections
    - content.footnote.tooltips
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - footnotes
  - admonition
  - pymdownx.details
  - def_list

